# Generated by Django 3.1.7 on 2024-06-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_movie_m_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='m_image',
        ),
    ]
